### ISSUE TITLE
Improve FEC user experience

### ISSUE THREAD

**Issue by hmacdope** [asapdiscovery/FALCBot#17]
Submitting FECs is currently not very user friendly, lets try and improve the user experience.

**Comment by JenkeScheen** [comment]
At this point the minimal information required is the name of the moleculeset and the target. we could have the command be something like `@falcbot run fep on <MoleculeSet name> for <Target>` as the most minimal/ easiest to remember form. 

If the user makes a mistake in the command we should return the correct formatting of the command. Alternatively, we could let the bot ask specifically what `<MoleculeSet name>` and `<Target>` is requested.

**Comment by hmacdope** [comment]
Improved but missing target information.
