### ISSUE TITLE
Deployment on AWS EC2

### ISSUE THREAD

**Issue by hmacdope** [asapdiscovery/FALCBot#8]
We will deploy an MVP on `EC2` rather than Lambda, as much easier to get started with. We can then evaluate a shift to a lambda based model.

**Comment by mikemhenry** [comment]
I saw on #4 you were concerned with secrets, AWS has a few different products to manage that, including a secret store that we can setup so that AWS Lambda can read from it (or an EC2 host can fetch it). How compute intensive is this?

**Comment by hmacdope** [comment]
Its not very compute hungry.

 It will be much more efficient as a lambda, but will require some fiddly re-architecting to get it to work.  I propose (and discussed with others) that we could just deploy on a cheap EC2 instance (e.g t4g medium $12/mo) for an MVP and work towards a lambda in the future. 
 
 What do you think?

**Comment by hmacdope** [comment]
Done
